import { applyArrivedDeliveries } from "./inventoryOrders";
import { canOpenRestaurant, deriveOperationalStatus, hasCompleteMenuItem } from "./openingRequirements";
import type { CustomerReview, DailyReport, FastFoodGame } from "./types";
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const firstNames=["Maya","Ethan","Olivia","Noah","Amelia","Lucas","Sofia","Leo","Nora","Mason","Ava","Elias","Lily","Oscar","Ella","Theo","Mila","Henry","Zoe","Adam","Freya","Max","Chloe","Finn","Ruby","Jack","Isla","Ben","Eva","Sam"];
const lastInitials=["A.","B.","C.","D.","E.","F.","G.","H.","J.","K.","L.","M.","N.","P.","R.","S.","T.","V.","W."];
const positive=["Fresh food and a surprisingly quick visit.","The meal was hot, tasty, and worth the price.","Friendly staff and the order was exactly right.","Really enjoyed the food today. I will be back.","Clean restaurant, good portions, and fast service.","The featured item was excellent and tasted fresh."];
const mixed=["The food was good, but the wait was longer than expected.","Nice meal overall, although service could be smoother.","Good enough for a quick stop, with room to improve.","Staff were polite, though the restaurant seemed understaffed."];
const lowStock=["Several items were unavailable, so I could not order what I wanted.","The restaurant was low on stock and the menu felt limited.","My first choice was sold out, which was disappointing.","Too many unavailable items today. Stock management needs work."];
const ownerShift=["The owner was friendly, but running the place alone made service slow.","Small independent atmosphere and good effort, though the menu was limited.","The owner handled everything personally. Nice food, long wait.","Charming solo service, but the restaurant clearly needs more staff."];
const negative=["The wait was too long and the meal did not feel worth it.","Service was slow and the order experience was frustrating.","The restaurant seemed unprepared for the number of customers.","Food quality and speed both need attention."];
function createReviews(count:number,day:number,satisfaction:number,stockPressure:number,waitTime:number,existing:CustomerReview[],ownerWorked:boolean):CustomerReview[]{
 const usedNames=new Set(existing.map(r=>r.name)),usedTexts=new Set(existing.map(r=>r.text)),out:CustomerReview[]=[];
 for(let i=0;i<count;i++){let name="";for(let a=0;a<80&&!name;a++){const candidate=`${firstNames[Math.floor(Math.random()*firstNames.length)]} ${lastInitials[Math.floor(Math.random()*lastInitials.length)]}`;if(!usedNames.has(candidate))name=candidate}if(!name)name=`Guest ${day}-${i+1}`;usedNames.add(name);
  const quality=satisfaction-stockPressure*20-(waitTime>11?8:0)+(Math.random()*12-6);const rating=clamp(Math.round(quality/20),1,5);let pool=ownerWorked?ownerShift:rating>=4?positive:rating===3?mixed:negative;if(stockPressure>.2)pool=lowStock;const text=pool.find(t=>!usedTexts.has(t))??`${pool[0]} Visit ${day}-${i+1}.`;usedTexts.add(text);out.push({id:crypto.randomUUID(),name,rating,text,day});}
 return out;
}
function closedReport(next:FastFoodGame,status:FastFoodGame["operationalStatus"],headline:string,notes:string[]):DailyReport{
 const maintenance=Math.round(next.equipment.reduce((s,e)=>s+e.maintenanceCost/60,0));const marketing=next.marketingDays>0?450:0;const expenses=next.rentDaily+maintenance+marketing;const attempted=next.marketingDays>0?Math.round(8+Math.random()*12):0;
 return {day:next.day,headline,operationalStatus:status,customersAttempted:attempted,customersServed:0,customersLost:attempted,revenue:0,foodCost:0,wages:0,rent:next.rentDaily,marketing,maintenance,waste:0,expenses,profit:-expenses,bestItem:"No sales",waitTime:0,satisfaction:0,reputationChange:0,valueChange:-Math.round(expenses*.12),notes};
}
export function simulateFastFoodDay(game:FastFoodGame):FastFoodGame{
 const next=applyArrivedDeliveries(structuredClone(game),game.day);next.operationalStatus=deriveOperationalStatus(next);
 const ownerWorked=next.ownerWorksNextShift;const normallyOpen=next.operationalStatus==="open"&&canOpenRestaurant(next);let report:DailyReport;
 if(!normallyOpen&&!ownerWorked){
  const missing=[];if(!next.selectedSupplierId)missing.push("Choose a supplier.");if(!next.employees.some(e=>e.role==="Cashier"))missing.push("Hire a cashier.");if(!next.employees.some(e=>e.role==="Kitchen Crew"||e.role==="Cook"))missing.push("Hire kitchen staff.");if(!hasCompleteMenuItem(next))missing.push("Receive ingredients for an active menu item.");
  const headline=next.operationalStatus==="closed"?"Restaurant remained closed":next.operationalStatus==="renovating"?"Renovation kept the restaurant closed":"Opening preparation incomplete";
  report=closedReport(next,next.operationalStatus,headline,[...missing,"No customers were served and no food-service reviews were generated.","Fixed costs were still charged for the day."]);
 }else{
  const active=next.menu.filter(i=>i.active&&Object.entries(i.ingredients).every(([id,use])=>use<=0||(next.inventory.find(x=>x.id===id)?.stock??0)>=use));
  const staffScore=ownerWorked?18:next.employees.reduce((s,e)=>s+e.skill+e.speed-e.fatigue/2,0)/Math.max(1,next.employees.length*2);const equipmentScore=next.equipment.reduce((s,e)=>s+e.condition,0)/next.equipment.length;
  const lowStockItems=next.inventory.filter(i=>i.stock<=i.reorder),stockPressure=lowStockItems.length/Math.max(next.inventory.length,1);const appearanceBonus=next.visualStage==="flagship"?7:next.visualStage==="premium"?5:next.visualStage==="drive-through"?4:next.visualStage==="established"?2:0;
  const attempted=Math.round(55+next.reputation*12+(next.marketingDays>0?24:0)+appearanceBonus+Math.random()*22);const roleCapacity=ownerWorked?Math.round(8+Math.random()*7):Math.round(next.capacity*clamp(staffScore/62,.2,1.15)*clamp(equipmentScore/80,.55,1.1));let served=Math.min(attempted,roleCapacity);
  let revenue=0,foodCost=0;const popularityTotal=Math.max(1,active.reduce((s,i)=>s+i.popularity,0));for(const item of active){let sales=Math.round(served*(item.popularity/popularityTotal)*(item.id==="drink"?1.15:1));for(const [id,use] of Object.entries(item.ingredients)){if(use>0){const inv=next.inventory.find(i=>i.id===id);sales=Math.min(sales,Math.floor((inv?.stock??0)/use));}}item.sales=Math.max(0,sales);revenue+=item.sales*item.price;foodCost+=item.sales*item.cost;for(const [id,use] of Object.entries(item.ingredients)){const inv=next.inventory.find(i=>i.id===id);if(inv)inv.stock=Math.max(0,inv.stock-item.sales*use)}}
  const totalSales=active.reduce((s,i)=>s+i.sales,0);if(totalSales===0)served=0;else served=Math.min(served,Math.max(1,Math.round(totalSales/(active.length>1?1.5:1))));
  const wages=ownerWorked?0:Math.round(next.employees.reduce((s,e)=>s+e.wage*8,0));const maintenance=Math.round(next.equipment.reduce((s,e)=>s+e.maintenanceCost/30,0));const marketing=next.marketingDays>0?450:0;const waste=Math.round(next.inventory.filter(i=>i.spoilage<7).reduce((s,i)=>s+i.stock*.006*i.unitCost,0));const expenses=Math.round(foodCost+wages+next.rentDaily+maintenance+marketing+waste);const profit=Math.round(revenue-expenses);const waitTime=ownerWorked?clamp(Math.round(16+Math.random()*5),15,22):clamp(Math.round(15-staffScore/7+attempted/38),2,22);const satisfaction=clamp(Math.round(74+next.reputation*4-waitTime*.7+(equipmentScore-80)*.15-stockPressure*22-(ownerWorked?4:0)),35,97);const repChange=(satisfaction-78)/220;
  const reviewCount=served===0?0:served<20?(Math.random()<.35?1:0):served<75?(Math.random()<.65?1:0):Math.max(1,Math.round(served/60));const generated=createReviews(reviewCount,next.day,satisfaction,stockPressure,waitTime,next.recentReviews,ownerWorked);const ratingAverage=generated.length?generated.reduce((s,r)=>s+r.rating,0)/generated.length:next.reputation;const totalReviews=next.reviews+generated.length;next.reputation=clamp(totalReviews?((next.reputation*next.reviews)+(ratingAverage*generated.length))/totalReviews+repChange*.18:next.reputation,1,5);next.reviews=totalReviews;next.recentReviews=[...generated,...next.recentReviews].slice(0,12);
  const valueChange=Math.round(profit*.45+(satisfaction-75)*60);const notes:string[]=[];if(ownerWorked)notes.push("You worked the restaurant alone. Service capacity was limited and wait times were high.");if(attempted-served>0)notes.push(`You lost ${attempted-served} customers because capacity, staffing or inventory was too low.`);if(lowStockItems.length)notes.push(`${lowStockItems.length} stock item${lowStockItems.length===1?" is":"s are"} at or below the reorder point.`);if(generated.length)notes.push(`${generated.length} new unique review${generated.length===1?" was":"s were"} posted.`);notes.push(profit>0?`The restaurant earned $${profit.toLocaleString("en-US")} after daily costs.`:`The restaurant lost $${Math.abs(profit).toLocaleString("en-US")} after daily costs.`);
  const best=[...active].sort((a,b)=>b.sales-a.sales)[0]?.name??"No sales";const headline=ownerWorked?"Owner-operated opening day":served===0?"Inventory shortages stopped service":profit>0?"Profitable day":profit===0?"Break-even day":"Loss-making day";
  report={day:next.day,headline,operationalStatus:ownerWorked?"open":next.operationalStatus,customersAttempted:attempted,customersServed:served,customersLost:Math.max(0,attempted-served),revenue:Math.round(revenue),foodCost:Math.round(foodCost),wages,rent:next.rentDaily,marketing,maintenance,waste,expenses,profit,bestItem:best,waitTime,satisfaction,reputationChange:repChange,valueChange,notes};
  const payoutRate=next.payoutPolicy==="None"?0:next.payoutPolicy==="Conservative"?.05:next.payoutPolicy==="Balanced"?.1:.2;const payout=Math.max(0,Math.round(profit*payoutRate));next.companyCash-=payout;next.personalCash+=payout;next.restaurantValue=Math.max(5000,next.restaurantValue+valueChange);next.companyValue=next.restaurantValue+Math.max(0,next.companyCash*.6);next.employees.forEach(e=>{e.fatigue=clamp(e.fatigue+6-Math.random()*4,0,100);e.mood=clamp(e.mood+(profit>0?1:-2),20,100);e.performance=clamp(Math.round((e.skill+e.speed+e.reliability+e.mood-e.fatigue)/4),20,100)});if(ownerWorked)next.founderFatigue=clamp(next.founderFatigue+24,0,100);
 }
 next.ownerWorksNextShift=false;next.reports=[report,...next.reports].slice(0,120);next.day+=1;next.weekday=(next.weekday+1)%7;if(next.day>30){next.day=1;next.month+=1}if(next.marketingDays>0)next.marketingDays-=1;next.companyCash+=report.profit;if(report.profit<0)next.restaurantValue=Math.max(5000,next.restaurantValue+report.valueChange);next.pendingDeliveries=next.pendingDeliveries.map(d=>Math.random()*100>(next.suppliers.find(s=>s.id===d.supplierId)?.lateRisk??0)?d:{...d,expectedDay:d.expectedDay+1});applyArrivedDeliveries(next,next.day);
 if(next.inventory.some(i=>i.stock<=i.reorder)&&next.operationalStatus==="open")next.notifications.unshift({id:crypto.randomUUID(),text:"Low stock requires attention before the next day.",section:"Inventory",read:false,severity:"warning"});return next;
}
