import type {
  ChildhoodTrait,
  DegreeProgram,
  Difficulty,
  FamilyBackground,
  Job,
  LifeGrowthAction,
  Origin,
  SkillDefinition,
} from "./types";

export const STORAGE_KEY = "chargedlife-save-v15";
export const ACTIONS_PER_YEAR = 3;

export const defaultOrigin: Origin = {
  country: "Norway",
  background: "Working Class",
  trait: "Ambitious",
  difficulty: "Normal",
};

export const countries = [
  "Norway",
  "United States",
  "United Kingdom",
  "Germany",
  "Netherlands",
  "Turkey",
  "Brazil",
  "Japan",
  "Canada",
  "Australia",
];

export const educationLevels = [
  "No Higher Education",
  "Certificate",
  "Bachelor Degree",
  "Master Degree",
  "Elite Degree",
];

export const familyBackgrounds: FamilyBackground[] = [
  {
    name: "Poor",
    startingCash: 250,
    healthBonus: -4,
    happinessBonus: -4,
    intelligenceBonus: 0,
    charismaBonus: 4,
    disciplineBonus: 6,
    luckBonus: 0,
    reputationBonus: 0,
    description:
      "You grew up with very little money, but learned how to survive early.",
  },
  {
    name: "Working Class",
    startingCash: 2500,
    healthBonus: 0,
    happinessBonus: 0,
    intelligenceBonus: 2,
    charismaBonus: 2,
    disciplineBonus: 5,
    luckBonus: 0,
    reputationBonus: 2,
    description:
      "You grew up in a normal hardworking family with modest opportunities.",
  },
  {
    name: "Middle Class",
    startingCash: 7500,
    healthBonus: 2,
    happinessBonus: 3,
    intelligenceBonus: 4,
    charismaBonus: 2,
    disciplineBonus: 2,
    luckBonus: 2,
    reputationBonus: 5,
    description:
      "You grew up stable, supported, and had access to decent opportunities.",
  },
  {
    name: "Wealthy",
    startingCash: 25000,
    healthBonus: 4,
    happinessBonus: 4,
    intelligenceBonus: 6,
    charismaBonus: 4,
    disciplineBonus: -2,
    luckBonus: 5,
    reputationBonus: 10,
    description:
      "You grew up with money, comfort, and strong opportunities from the start.",
  },
  {
    name: "Rich Kid",
    startingCash: 75000,
    healthBonus: 5,
    happinessBonus: 2,
    intelligenceBonus: 4,
    charismaBonus: 7,
    disciplineBonus: -8,
    luckBonus: 8,
    reputationBonus: 18,
    description:
      "You were born into serious money, but discipline may become your biggest weakness.",
  },
];

export const childhoodTraits: ChildhoodTrait[] = [
  {
    name: "Ambitious",
    healthBonus: 0,
    happinessBonus: -2,
    intelligenceBonus: 2,
    charismaBonus: 0,
    disciplineBonus: 8,
    luckBonus: 0,
    reputationBonus: 2,
    description: "You always wanted more than an average life.",
  },
  {
    name: "Street Smart",
    healthBonus: 0,
    happinessBonus: 0,
    intelligenceBonus: 0,
    charismaBonus: 8,
    disciplineBonus: 2,
    luckBonus: 4,
    reputationBonus: 0,
    description:
      "You learned how people work before you learned how books work.",
  },
  {
    name: "Bookworm",
    healthBonus: -2,
    happinessBonus: 0,
    intelligenceBonus: 10,
    charismaBonus: -2,
    disciplineBonus: 4,
    luckBonus: 0,
    reputationBonus: 0,
    description: "You spent your childhood learning, reading, and thinking.",
  },
  {
    name: "Natural Leader",
    healthBonus: 0,
    happinessBonus: 2,
    intelligenceBonus: 2,
    charismaBonus: 8,
    disciplineBonus: 2,
    luckBonus: 0,
    reputationBonus: 6,
    description: "People naturally listened when you spoke.",
  },
  {
    name: "Lucky",
    healthBonus: 0,
    happinessBonus: 2,
    intelligenceBonus: 0,
    charismaBonus: 0,
    disciplineBonus: 0,
    luckBonus: 15,
    reputationBonus: 0,
    description: "Things had a strange way of working out for you.",
  },
  {
    name: "Reckless",
    healthBonus: -3,
    happinessBonus: 5,
    intelligenceBonus: 0,
    charismaBonus: 5,
    disciplineBonus: -6,
    luckBonus: 5,
    reputationBonus: -2,
    description: "You were bold, chaotic, and not afraid of consequences.",
  },
  {
    name: "Disciplined",
    healthBonus: 3,
    happinessBonus: -1,
    intelligenceBonus: 2,
    charismaBonus: 0,
    disciplineBonus: 12,
    luckBonus: 0,
    reputationBonus: 2,
    description: "You were consistent even when life was boring.",
  },
  {
    name: "Creative",
    healthBonus: 0,
    happinessBonus: 4,
    intelligenceBonus: 4,
    charismaBonus: 4,
    disciplineBonus: -1,
    luckBonus: 2,
    reputationBonus: 1,
    description: "You saw opportunities and ideas other people missed.",
  },
];

export const difficulties: Difficulty[] = [
  {
    name: "Easy",
    cashMultiplier: 1.4,
    statPenalty: 0,
    description: "More forgiving start. Good for testing and casual play.",
  },
  {
    name: "Normal",
    cashMultiplier: 1,
    statPenalty: 0,
    description: "Balanced ChargedLife experience.",
  },
  {
    name: "Hard",
    cashMultiplier: 0.65,
    statPenalty: 5,
    description: "Less money and weaker starting stats. Every choice matters.",
  },
  {
    name: "Brutal",
    cashMultiplier: 0.35,
    statPenalty: 10,
    description: "A painful start for people who want the challenge.",
  },
];

export const skills: SkillDefinition[] = [
  {
    id: "business",
    name: "Business",
    description: "Helps with leadership, promotions, and building companies.",
    primaryStat: "discipline",
    secondaryStat: "charisma",
  },
  {
    id: "marketing",
    name: "Marketing",
    description: "Helps with sales, brand building, and reputation.",
    primaryStat: "charisma",
    secondaryStat: "reputation",
  },
  {
    id: "programming",
    name: "Programming",
    description: "Unlocks tech jobs, startups, and high-income careers.",
    primaryStat: "intelligence",
    secondaryStat: "discipline",
  },
  {
    id: "finance",
    name: "Finance",
    description: "Improves investing and unlocks finance careers.",
    primaryStat: "intelligence",
    secondaryStat: "discipline",
  },
  {
    id: "realEstate",
    name: "Real Estate",
    description: "Helps with property, deals, and long-term wealth.",
    primaryStat: "charisma",
    secondaryStat: "discipline",
  },
  {
    id: "content",
    name: "Content Creation",
    description: "Helps with fame, reputation, and online business.",
    primaryStat: "charisma",
    secondaryStat: "reputation",
  },
  {
    id: "medical",
    name: "Medical",
    description: "Unlocks healthcare careers with high discipline requirements.",
    primaryStat: "intelligence",
    secondaryStat: "discipline",
  },
  {
    id: "law",
    name: "Law",
    description: "Unlocks legal careers and reputation-heavy jobs.",
    primaryStat: "intelligence",
    secondaryStat: "reputation",
  },
  {
    id: "engineering",
    name: "Engineering",
    description: "Unlocks engineering and advanced technical jobs.",
    primaryStat: "intelligence",
    secondaryStat: "discipline",
  },
];

export const lifeGrowthActions: LifeGrowthAction[] = [
  {
    id: "rest",
    category: "health",
    name: "Rest",
    description: "Recover your body and mind.",
    healthGain: 10,
    happinessGain: 6,
    intelligenceGain: 0,
    charismaGain: 0,
    disciplineGain: -1,
    reputationGain: 0,
    cashCost: 0,
  },
  {
    id: "go-gym",
    category: "health",
    name: "Go to Gym",
    description: "Build health, confidence, and discipline.",
    healthGain: 8,
    happinessGain: 1,
    intelligenceGain: 0,
    charismaGain: 1,
    disciplineGain: 4,
    reputationGain: 0,
    cashCost: 300,
  },
  {
    id: "therapy",
    category: "mental",
    name: "Go to Therapy",
    description: "Improve happiness and handle life pressure.",
    healthGain: 1,
    happinessGain: 12,
    intelligenceGain: 0,
    charismaGain: 0,
    disciplineGain: 1,
    reputationGain: 0,
    cashCost: 1000,
  },
  {
    id: "meditate",
    category: "mental",
    name: "Meditate",
    description: "Calm down and build discipline.",
    healthGain: 2,
    happinessGain: 7,
    intelligenceGain: 0,
    charismaGain: 0,
    disciplineGain: 3,
    reputationGain: 0,
    cashCost: 0,
  },
  {
    id: "take-vacation",
    category: "mental",
    name: "Take Vacation",
    description: "Expensive, but great for happiness and health.",
    healthGain: 5,
    happinessGain: 15,
    intelligenceGain: 0,
    charismaGain: 1,
    disciplineGain: -2,
    reputationGain: 0,
    cashCost: 2500,
  },
  {
    id: "socialize",
    category: "social",
    name: "Socialize",
    description: "Spend time with people and improve your social life.",
    healthGain: 0,
    happinessGain: 6,
    intelligenceGain: 0,
    charismaGain: 5,
    disciplineGain: 0,
    reputationGain: 2,
    cashCost: 500,
  },
  {
    id: "network",
    category: "social",
    name: "Network",
    description: "Meet useful people and create opportunities.",
    healthGain: 0,
    happinessGain: 2,
    intelligenceGain: 0,
    charismaGain: 4,
    disciplineGain: 0,
    reputationGain: 6,
    cashCost: 750,
  },
  {
    id: "family-time",
    category: "social",
    name: "Family Time",
    description: "Spend time with family and recover happiness.",
    healthGain: 1,
    happinessGain: 9,
    intelligenceGain: 0,
    charismaGain: 1,
    disciplineGain: 0,
    reputationGain: 0,
    cashCost: 250,
  },
  {
    id: "read-books",
    category: "growth",
    name: "Read Books",
    description: "Improve intelligence and discipline.",
    healthGain: 0,
    happinessGain: 0,
    intelligenceGain: 7,
    charismaGain: 0,
    disciplineGain: 3,
    reputationGain: 0,
    cashCost: 0,
  },
  {
    id: "practice-speaking",
    category: "growth",
    name: "Practice Speaking",
    description: "Improve charisma and reputation.",
    healthGain: 0,
    happinessGain: 1,
    intelligenceGain: 0,
    charismaGain: 7,
    disciplineGain: 1,
    reputationGain: 3,
    cashCost: 0,
  },
  {
    id: "build-discipline",
    category: "growth",
    name: "Build Discipline",
    description: "Create routines and become more consistent.",
    healthGain: 1,
    happinessGain: -1,
    intelligenceGain: 1,
    charismaGain: 0,
    disciplineGain: 8,
    reputationGain: 1,
    cashCost: 0,
  },
  {
    id: "confidence-training",
    category: "growth",
    name: "Confidence Training",
    description: "Improve charisma and mental strength.",
    healthGain: 0,
    happinessGain: 4,
    intelligenceGain: 0,
    charismaGain: 6,
    disciplineGain: 2,
    reputationGain: 2,
    cashCost: 600,
  },
];

export const selfImprovementActions = lifeGrowthActions;

export const degreePrograms: DegreeProgram[] = [
  {
    id: "business-administration",
    schoolCategory: "business",
    schoolName: "Business School",
    name: "Business Administration Degree",
    description: "A general business degree for management and leadership jobs.",
    totalCost: 20000,
    happinessCost: 4,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Business Administration Degree",
    skillReward: "business",
    skillGainOnComplete: 4,
    intelligenceGain: 2,
    charismaGain: 2,
    disciplineGain: 3,
    reputationGain: 3,
  },
  {
    id: "management-degree",
    schoolCategory: "business",
    schoolName: "Business School",
    name: "Management Degree",
    description: "Focused on teams, operations, and promotions.",
    totalCost: 22000,
    happinessCost: 4,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Management Degree",
    skillReward: "business",
    skillGainOnComplete: 5,
    intelligenceGain: 2,
    charismaGain: 3,
    disciplineGain: 4,
    reputationGain: 3,
    requiredDegree: "business-administration",
  },
  {
    id: "entrepreneurship",
    schoolCategory: "business",
    schoolName: "Business School",
    name: "Entrepreneurship Degree",
    description: "Focused on starting companies, risk, and growth.",
    totalCost: 30000,
    happinessCost: 5,
    progressGain: 34,
    educationLevelReward: 3,
    educationName: "Entrepreneurship Degree",
    skillReward: "business",
    skillGainOnComplete: 6,
    intelligenceGain: 3,
    charismaGain: 3,
    disciplineGain: 3,
    reputationGain: 5,
    requiredDegree: "business-administration",
  },
  {
    id: "executive-mba",
    schoolCategory: "business",
    schoolName: "Business School",
    name: "Executive MBA",
    description: "Elite business education for CEO and top executive careers.",
    totalCost: 75000,
    happinessCost: 8,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Executive MBA",
    skillReward: "business",
    skillGainOnComplete: 8,
    intelligenceGain: 5,
    charismaGain: 5,
    disciplineGain: 5,
    reputationGain: 8,
    requiredDegree: "entrepreneurship",
  },
  {
    id: "marketing-degree",
    schoolCategory: "business",
    schoolName: "Business School",
    name: "Marketing & Sales Degree",
    description: "Focused on sales, branding, and marketing careers.",
    totalCost: 18000,
    happinessCost: 4,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Marketing & Sales Degree",
    skillReward: "marketing",
    skillGainOnComplete: 4,
    intelligenceGain: 1,
    charismaGain: 5,
    disciplineGain: 1,
    reputationGain: 4,
  },
  {
    id: "executive-marketing-mba",
    schoolCategory: "business",
    schoolName: "Business School",
    name: "Executive Marketing MBA",
    description: "Elite marketing education for CMO and top brand leadership.",
    totalCost: 70000,
    happinessCost: 8,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Executive Marketing MBA",
    skillReward: "marketing",
    skillGainOnComplete: 8,
    intelligenceGain: 4,
    charismaGain: 7,
    disciplineGain: 4,
    reputationGain: 8,
    requiredDegree: "marketing-degree",
  },

  {
    id: "finance-accounting",
    schoolCategory: "finance",
    schoolName: "Finance School",
    name: "Finance & Accounting Degree",
    description: "Focused on banking, investing, and corporate finance.",
    totalCost: 28000,
    happinessCost: 6,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Finance & Accounting Degree",
    skillReward: "finance",
    skillGainOnComplete: 4,
    intelligenceGain: 4,
    charismaGain: 1,
    disciplineGain: 4,
    reputationGain: 2,
  },
  {
    id: "investment-degree",
    schoolCategory: "finance",
    schoolName: "Finance School",
    name: "Investment Banking Degree",
    description: "A harder finance path for high-paying finance jobs.",
    totalCost: 45000,
    happinessCost: 7,
    progressGain: 34,
    educationLevelReward: 3,
    educationName: "Investment Banking Degree",
    skillReward: "finance",
    skillGainOnComplete: 6,
    intelligenceGain: 5,
    charismaGain: 2,
    disciplineGain: 5,
    reputationGain: 4,
    requiredDegree: "finance-accounting",
  },
  {
    id: "executive-finance-mba",
    schoolCategory: "finance",
    schoolName: "Finance School",
    name: "Executive Finance MBA",
    description: "Elite finance education for CFO and top finance careers.",
    totalCost: 80000,
    happinessCost: 8,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Executive Finance MBA",
    skillReward: "finance",
    skillGainOnComplete: 8,
    intelligenceGain: 6,
    charismaGain: 3,
    disciplineGain: 6,
    reputationGain: 7,
    requiredDegree: "investment-degree",
  },

  {
    id: "computer-science",
    schoolCategory: "tech",
    schoolName: "Tech School",
    name: "Computer Science Degree",
    description: "Unlocks programming, software, and tech careers.",
    totalCost: 30000,
    happinessCost: 6,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Computer Science Degree",
    skillReward: "programming",
    skillGainOnComplete: 4,
    intelligenceGain: 5,
    charismaGain: 0,
    disciplineGain: 4,
    reputationGain: 2,
  },
  {
    id: "software-engineering",
    schoolCategory: "tech",
    schoolName: "Tech School",
    name: "Software Engineering Degree",
    description: "A stronger tech degree for senior developer and CTO paths.",
    totalCost: 45000,
    happinessCost: 7,
    progressGain: 34,
    educationLevelReward: 3,
    educationName: "Software Engineering Degree",
    skillReward: "programming",
    skillGainOnComplete: 6,
    intelligenceGain: 6,
    charismaGain: 0,
    disciplineGain: 5,
    reputationGain: 3,
    requiredDegree: "computer-science",
  },
  {
    id: "executive-tech-mba",
    schoolCategory: "tech",
    schoolName: "Tech School",
    name: "Executive Tech MBA",
    description: "Elite tech leadership education for CTO and tech executive paths.",
    totalCost: 85000,
    happinessCost: 8,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Executive Tech MBA",
    skillReward: "programming",
    skillGainOnComplete: 8,
    intelligenceGain: 7,
    charismaGain: 3,
    disciplineGain: 6,
    reputationGain: 7,
    requiredDegree: "software-engineering",
  },
  {
    id: "game-development",
    schoolCategory: "tech",
    schoolName: "Tech School",
    name: "Game Development Degree",
    description: "Useful for future game studio and creative tech paths.",
    totalCost: 35000,
    happinessCost: 6,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Game Development Degree",
    skillReward: "programming",
    skillGainOnComplete: 4,
    intelligenceGain: 4,
    charismaGain: 1,
    disciplineGain: 3,
    reputationGain: 3,
    requiredDegree: "computer-science",
  },

  {
    id: "nursing-degree",
    schoolCategory: "medical",
    schoolName: "Medical School",
    name: "Nursing Degree",
    description: "A cheaper medical path for nursing careers.",
    totalCost: 45000,
    happinessCost: 7,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Nursing Degree",
    skillReward: "medical",
    skillGainOnComplete: 3,
    intelligenceGain: 4,
    charismaGain: 1,
    disciplineGain: 4,
    reputationGain: 3,
  },
  {
    id: "medical-degree",
    schoolCategory: "medical",
    schoolName: "Medical School",
    name: "Medical Degree",
    description: "Very expensive, but unlocks doctor careers.",
    totalCost: 120000,
    happinessCost: 10,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Medical Degree",
    skillReward: "medical",
    skillGainOnComplete: 6,
    intelligenceGain: 6,
    charismaGain: 0,
    disciplineGain: 6,
    reputationGain: 6,
  },
  {
    id: "surgery-specialization",
    schoolCategory: "medical",
    schoolName: "Medical School",
    name: "Surgery Specialization",
    description: "Advanced medical path for surgeon careers.",
    totalCost: 180000,
    happinessCost: 12,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Surgery Specialization",
    skillReward: "medical",
    skillGainOnComplete: 8,
    intelligenceGain: 7,
    charismaGain: 0,
    disciplineGain: 8,
    reputationGain: 8,
    requiredDegree: "medical-degree",
  },

  {
    id: "legal-studies",
    schoolCategory: "law",
    schoolName: "Law School",
    name: "Legal Studies Degree",
    description: "A cheaper legal path for assistant and paralegal careers.",
    totalCost: 35000,
    happinessCost: 5,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Legal Studies Degree",
    skillReward: "law",
    skillGainOnComplete: 3,
    intelligenceGain: 3,
    charismaGain: 2,
    disciplineGain: 2,
    reputationGain: 3,
  },
  {
    id: "law-degree",
    schoolCategory: "law",
    schoolName: "Law School",
    name: "Law Degree",
    description: "Unlocks lawyer, partner, and judge paths.",
    totalCost: 85000,
    happinessCost: 8,
    progressGain: 34,
    educationLevelReward: 3,
    educationName: "Law Degree",
    skillReward: "law",
    skillGainOnComplete: 5,
    intelligenceGain: 5,
    charismaGain: 3,
    disciplineGain: 3,
    reputationGain: 6,
    requiredDegree: "legal-studies",
  },
  {
    id: "judicial-studies",
    schoolCategory: "law",
    schoolName: "Law School",
    name: "Judicial Studies Degree",
    description: "Elite law path for judge and high-level legal careers.",
    totalCost: 90000,
    happinessCost: 8,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Judicial Studies Degree",
    skillReward: "law",
    skillGainOnComplete: 8,
    intelligenceGain: 6,
    charismaGain: 4,
    disciplineGain: 6,
    reputationGain: 8,
    requiredDegree: "law-degree",
  },

  {
    id: "real-estate-license",
    schoolCategory: "realEstate",
    schoolName: "Real Estate School",
    name: "Real Estate License",
    description: "Unlocks property and real estate careers.",
    totalCost: 10000,
    happinessCost: 3,
    progressGain: 34,
    educationLevelReward: 1,
    educationName: "Real Estate License",
    skillReward: "realEstate",
    skillGainOnComplete: 3,
    intelligenceGain: 1,
    charismaGain: 4,
    disciplineGain: 2,
    reputationGain: 3,
  },
  {
    id: "property-development",
    schoolCategory: "realEstate",
    schoolName: "Real Estate School",
    name: "Property Development Degree",
    description: "Advanced real estate education for developer and mogul paths.",
    totalCost: 50000,
    happinessCost: 6,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Property Development Degree",
    skillReward: "realEstate",
    skillGainOnComplete: 6,
    intelligenceGain: 3,
    charismaGain: 4,
    disciplineGain: 4,
    reputationGain: 5,
    requiredDegree: "real-estate-license",
  },
  {
    id: "real-estate-mba",
    schoolCategory: "realEstate",
    schoolName: "Real Estate School",
    name: "Real Estate MBA",
    description: "Elite property education for real estate mogul careers.",
    totalCost: 85000,
    happinessCost: 8,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Real Estate MBA",
    skillReward: "realEstate",
    skillGainOnComplete: 8,
    intelligenceGain: 5,
    charismaGain: 6,
    disciplineGain: 6,
    reputationGain: 8,
    requiredDegree: "property-development",
  },

  {
    id: "media-degree",
    schoolCategory: "creative",
    schoolName: "Creative School",
    name: "Media Degree",
    description: "Unlocks content, creative, and influencer careers.",
    totalCost: 18000,
    happinessCost: 4,
    progressGain: 34,
    educationLevelReward: 1,
    educationName: "Media Degree",
    skillReward: "content",
    skillGainOnComplete: 4,
    intelligenceGain: 1,
    charismaGain: 5,
    disciplineGain: 1,
    reputationGain: 5,
  },
  {
    id: "creative-business",
    schoolCategory: "creative",
    schoolName: "Creative School",
    name: "Creative Business Degree",
    description: "Useful for creators who want to become entrepreneurs.",
    totalCost: 30000,
    happinessCost: 5,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Creative Business Degree",
    skillReward: "content",
    skillGainOnComplete: 5,
    intelligenceGain: 2,
    charismaGain: 5,
    disciplineGain: 2,
    reputationGain: 6,
    requiredDegree: "media-degree",
  },
  {
    id: "celebrity-business-mba",
    schoolCategory: "creative",
    schoolName: "Creative School",
    name: "Celebrity Business MBA",
    description: "Elite creator education for celebrity entrepreneur careers.",
    totalCost: 90000,
    happinessCost: 8,
    progressGain: 34,
    educationLevelReward: 4,
    educationName: "Celebrity Business MBA",
    skillReward: "content",
    skillGainOnComplete: 8,
    intelligenceGain: 4,
    charismaGain: 8,
    disciplineGain: 5,
    reputationGain: 10,
    requiredDegree: "creative-business",
  },

  {
    id: "engineering-degree",
    schoolCategory: "engineering",
    schoolName: "Engineering School",
    name: "Engineering Degree",
    description: "Unlocks engineering and advanced technical careers.",
    totalCost: 45000,
    happinessCost: 7,
    progressGain: 34,
    educationLevelReward: 2,
    educationName: "Engineering Degree",
    skillReward: "engineering",
    skillGainOnComplete: 5,
    intelligenceGain: 6,
    charismaGain: 0,
    disciplineGain: 5,
    reputationGain: 3,
  },
];

export const jobs: Job[] = [
  {
    id: "part-time-cafe",
    title: "Part-Time Cafe Worker",
    category: "partTime",
    careerPath: "Part-Time",
    track: "business",
    salary: 12000,
    employmentType: "partTime",
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredIntelligence: 10,
    requiredCharisma: 10,
    requiredDiscipline: 10,
    requiredReputation: 0,
  },
  {
    id: "part-time-tutor",
    title: "Part-Time Tutor",
    category: "partTime",
    careerPath: "Part-Time",
    track: "content",
    salary: 18000,
    employmentType: "partTime",
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredIntelligence: 45,
    requiredCharisma: 20,
    requiredDiscipline: 25,
    requiredReputation: 0,
  },
  {
    id: "part-time-delivery",
    title: "Part-Time Delivery Driver",
    category: "partTime",
    careerPath: "Part-Time",
    track: "business",
    salary: 16000,
    employmentType: "partTime",
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredIntelligence: 15,
    requiredCharisma: 10,
    requiredDiscipline: 20,
    requiredReputation: 0,
  },
  {
    id: "retail-worker",
    title: "Retail Worker",
    category: "starter",
    careerPath: "Retail",
    nextJobId: "senior-retail-worker",
    track: "business",
    salary: 25000,
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredIntelligence: 20,
    requiredCharisma: 20,
    requiredDiscipline: 20,
    requiredReputation: 0,
  },
  {
    id: "senior-retail-worker",
    title: "Senior Retail Worker",
    category: "starter",
    careerPath: "Retail",
    nextJobId: "store-supervisor",
    track: "business",
    salary: 34000,
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredJobId: "retail-worker",
    requiredJobExperience: 2,
    requiredIntelligence: 25,
    requiredCharisma: 28,
    requiredDiscipline: 35,
    requiredReputation: 5,
  },
  {
    id: "store-supervisor",
    title: "Store Supervisor",
    category: "starter",
    careerPath: "Retail",
    nextJobId: "store-manager",
    track: "business",
    salary: 43000,
    requiredSkill: 1,
    requiredEducationLevel: 0,
    requiredJobId: "senior-retail-worker",
    requiredJobExperience: 2,
    requiredIntelligence: 32,
    requiredCharisma: 35,
    requiredDiscipline: 42,
    requiredReputation: 10,
  },
  {
    id: "store-manager",
    title: "Store Manager",
    category: "starter",
    careerPath: "Retail",
    track: "business",
    salary: 56000,
    requiredSkill: 2,
    requiredEducationLevel: 0,
    requiredJobId: "store-supervisor",
    requiredJobExperience: 2,
    requiredIntelligence: 40,
    requiredCharisma: 45,
    requiredDiscipline: 50,
    requiredReputation: 18,
  },
  {
    id: "fast-food-worker",
    title: "Fast Food Worker",
    category: "starter",
    careerPath: "Fast Food",
    nextJobId: "shift-leader",
    track: "business",
    salary: 23000,
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredIntelligence: 15,
    requiredCharisma: 15,
    requiredDiscipline: 15,
    requiredReputation: 0,
  },
  {
    id: "shift-leader",
    title: "Shift Leader",
    category: "starter",
    careerPath: "Fast Food",
    nextJobId: "restaurant-manager",
    track: "business",
    salary: 33000,
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredJobId: "fast-food-worker",
    requiredJobExperience: 2,
    requiredIntelligence: 25,
    requiredCharisma: 25,
    requiredDiscipline: 35,
    requiredReputation: 5,
  },
  {
    id: "restaurant-manager",
    title: "Restaurant Manager",
    category: "starter",
    careerPath: "Fast Food",
    track: "business",
    salary: 52000,
    requiredSkill: 2,
    requiredEducationLevel: 0,
    requiredJobId: "shift-leader",
    requiredJobExperience: 2,
    requiredIntelligence: 40,
    requiredCharisma: 42,
    requiredDiscipline: 50,
    requiredReputation: 18,
  },
  {
    id: "warehouse-worker",
    title: "Warehouse Worker",
    category: "starter",
    careerPath: "Warehouse",
    nextJobId: "warehouse-supervisor",
    track: "business",
    salary: 30000,
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredIntelligence: 15,
    requiredCharisma: 10,
    requiredDiscipline: 25,
    requiredReputation: 0,
  },
  {
    id: "warehouse-supervisor",
    title: "Warehouse Supervisor",
    category: "starter",
    careerPath: "Warehouse",
    track: "business",
    salary: 48000,
    requiredSkill: 1,
    requiredEducationLevel: 0,
    requiredJobId: "warehouse-worker",
    requiredJobExperience: 2,
    requiredIntelligence: 35,
    requiredCharisma: 25,
    requiredDiscipline: 50,
    requiredReputation: 12,
  },
  {
    id: "delivery-driver",
    title: "Delivery Driver",
    category: "starter",
    careerPath: "Delivery",
    track: "business",
    salary: 32000,
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredIntelligence: 20,
    requiredCharisma: 15,
    requiredDiscipline: 25,
    requiredReputation: 0,
  },
  {
    id: "customer-support-agent",
    title: "Customer Support Agent",
    category: "starter",
    careerPath: "Customer Support",
    nextJobId: "senior-support-agent",
    track: "marketing",
    salary: 34000,
    requiredSkill: 0,
    requiredEducationLevel: 0,
    requiredIntelligence: 25,
    requiredCharisma: 30,
    requiredDiscipline: 20,
    requiredReputation: 0,
  },
  {
    id: "senior-support-agent",
    title: "Senior Support Agent",
    category: "starter",
    careerPath: "Customer Support",
    track: "marketing",
    salary: 46000,
    requiredSkill: 1,
    requiredEducationLevel: 0,
    requiredJobId: "customer-support-agent",
    requiredJobExperience: 2,
    requiredIntelligence: 35,
    requiredCharisma: 45,
    requiredDiscipline: 35,
    requiredReputation: 12,
  },

  {
    id: "sales-representative",
    title: "Sales Representative",
    category: "marketing",
    careerPath: "Marketing",
    nextJobId: "junior-marketer",
    track: "marketing",
    salary: 45000,
    requiredSkill: 1,
    requiredEducationLevel: 0,
    requiredIntelligence: 30,
    requiredCharisma: 40,
    requiredDiscipline: 25,
    requiredReputation: 5,
  },
  {
    id: "junior-marketer",
    title: "Junior Marketer",
    category: "marketing",
    careerPath: "Marketing",
    nextJobId: "marketing-director",
    track: "marketing",
    salary: 58000,
    requiredSkill: 2,
    requiredEducationLevel: 1,
    requiredDegree: "marketing-degree",
    requiredJobId: "sales-representative",
    requiredJobExperience: 2,
    requiredIntelligence: 42,
    requiredCharisma: 45,
    requiredDiscipline: 30,
    requiredReputation: 12,
  },
  {
    id: "marketing-director",
    title: "Marketing Director",
    category: "marketing",
    careerPath: "Marketing",
    nextJobId: "cmo",
    track: "marketing",
    salary: 125000,
    requiredSkill: 5,
    requiredEducationLevel: 2,
    requiredDegree: "marketing-degree",
    requiredJobId: "junior-marketer",
    requiredJobExperience: 3,
    requiredIntelligence: 62,
    requiredCharisma: 68,
    requiredDiscipline: 55,
    requiredReputation: 45,
  },
  {
    id: "cmo",
    title: "CMO",
    category: "marketing",
    careerPath: "Marketing",
    track: "marketing",
    salary: 220000,
    requiredSkill: 8,
    requiredEducationLevel: 4,
    requiredDegree: "executive-marketing-mba",
    requiredJobId: "marketing-director",
    requiredJobExperience: 3,
    requiredIntelligence: 72,
    requiredCharisma: 82,
    requiredDiscipline: 65,
    requiredReputation: 70,
  },

  {
    id: "it-support",
    title: "IT Support",
    category: "tech",
    careerPath: "Tech",
    nextJobId: "software-intern",
    track: "programming",
    salary: 48000,
    requiredSkill: 1,
    requiredEducationLevel: 0,
    requiredIntelligence: 40,
    requiredCharisma: 20,
    requiredDiscipline: 35,
    requiredReputation: 0,
  },
  {
    id: "software-intern",
    title: "Software Intern",
    category: "tech",
    careerPath: "Tech",
    nextJobId: "software-developer",
    track: "programming",
    salary: 52000,
    requiredSkill: 2,
    requiredEducationLevel: 1,
    requiredJobId: "it-support",
    requiredJobExperience: 1,
    requiredIntelligence: 48,
    requiredCharisma: 20,
    requiredDiscipline: 42,
    requiredReputation: 0,
  },
  {
    id: "software-developer",
    title: "Software Developer",
    category: "tech",
    careerPath: "Tech",
    nextJobId: "senior-developer",
    track: "programming",
    salary: 85000,
    requiredSkill: 4,
    requiredEducationLevel: 2,
    requiredDegree: "computer-science",
    requiredJobId: "software-intern",
    requiredJobExperience: 2,
    requiredIntelligence: 62,
    requiredCharisma: 25,
    requiredDiscipline: 55,
    requiredReputation: 15,
  },
  {
    id: "senior-developer",
    title: "Senior Developer",
    category: "tech",
    careerPath: "Tech",
    nextJobId: "cto",
    track: "programming",
    salary: 135000,
    requiredSkill: 6,
    requiredEducationLevel: 3,
    requiredDegree: "software-engineering",
    requiredJobId: "software-developer",
    requiredJobExperience: 3,
    requiredIntelligence: 75,
    requiredCharisma: 35,
    requiredDiscipline: 68,
    requiredReputation: 35,
  },
  {
    id: "cto",
    title: "CTO",
    category: "tech",
    careerPath: "Tech",
    track: "programming",
    salary: 220000,
    requiredSkill: 8,
    requiredEducationLevel: 4,
    requiredDegree: "executive-tech-mba",
    requiredJobId: "senior-developer",
    requiredJobExperience: 3,
    requiredIntelligence: 82,
    requiredCharisma: 55,
    requiredDiscipline: 75,
    requiredReputation: 60,
  },

  {
    id: "team-leader",
    title: "Team Leader",
    category: "business",
    careerPath: "Business",
    nextJobId: "business-manager",
    track: "business",
    salary: 65000,
    requiredSkill: 2,
    requiredEducationLevel: 1,
    requiredIntelligence: 42,
    requiredCharisma: 45,
    requiredDiscipline: 45,
    requiredReputation: 15,
  },
  {
    id: "business-manager",
    title: "Business Manager",
    category: "business",
    careerPath: "Business",
    nextJobId: "operations-manager",
    track: "business",
    salary: 105000,
    requiredSkill: 4,
    requiredEducationLevel: 2,
    requiredDegree: "business-administration",
    requiredJobId: "team-leader",
    requiredJobExperience: 2,
    requiredIntelligence: 58,
    requiredCharisma: 55,
    requiredDiscipline: 55,
    requiredReputation: 35,
  },
  {
    id: "operations-manager",
    title: "Operations Manager",
    category: "business",
    careerPath: "Business",
    nextJobId: "startup-executive",
    track: "business",
    salary: 125000,
    requiredSkill: 5,
    requiredEducationLevel: 2,
    requiredDegree: "management-degree",
    requiredJobId: "business-manager",
    requiredJobExperience: 2,
    requiredIntelligence: 62,
    requiredCharisma: 58,
    requiredDiscipline: 65,
    requiredReputation: 42,
  },
  {
    id: "startup-executive",
    title: "Startup Executive",
    category: "business",
    careerPath: "Business",
    nextJobId: "ceo",
    track: "business",
    salary: 155000,
    requiredSkill: 6,
    requiredEducationLevel: 3,
    requiredDegree: "entrepreneurship",
    requiredJobId: "operations-manager",
    requiredJobExperience: 3,
    requiredIntelligence: 70,
    requiredCharisma: 65,
    requiredDiscipline: 60,
    requiredReputation: 50,
  },
  {
    id: "ceo",
    title: "CEO",
    category: "business",
    careerPath: "Business",
    track: "business",
    salary: 275000,
    requiredSkill: 8,
    requiredEducationLevel: 4,
    requiredDegree: "executive-mba",
    requiredJobId: "startup-executive",
    requiredJobExperience: 3,
    requiredIntelligence: 82,
    requiredCharisma: 76,
    requiredDiscipline: 70,
    requiredReputation: 72,
  },

  {
    id: "bank-teller",
    title: "Bank Teller",
    category: "finance",
    careerPath: "Finance",
    nextJobId: "financial-analyst",
    track: "finance",
    salary: 42000,
    requiredSkill: 1,
    requiredEducationLevel: 0,
    requiredIntelligence: 35,
    requiredCharisma: 25,
    requiredDiscipline: 35,
    requiredReputation: 0,
  },
  {
    id: "financial-analyst",
    title: "Financial Analyst",
    category: "finance",
    careerPath: "Finance",
    nextJobId: "investment-banker",
    track: "finance",
    salary: 80000,
    requiredSkill: 4,
    requiredEducationLevel: 2,
    requiredDegree: "finance-accounting",
    requiredJobId: "bank-teller",
    requiredJobExperience: 2,
    requiredIntelligence: 60,
    requiredCharisma: 30,
    requiredDiscipline: 55,
    requiredReputation: 15,
  },
  {
    id: "investment-banker",
    title: "Investment Banker",
    category: "finance",
    careerPath: "Finance",
    nextJobId: "cfo",
    track: "finance",
    salary: 145000,
    requiredSkill: 6,
    requiredEducationLevel: 3,
    requiredDegree: "investment-degree",
    requiredJobId: "financial-analyst",
    requiredJobExperience: 3,
    requiredIntelligence: 78,
    requiredCharisma: 45,
    requiredDiscipline: 70,
    requiredReputation: 45,
  },
  {
    id: "cfo",
    title: "CFO",
    category: "finance",
    careerPath: "Finance",
    track: "finance",
    salary: 230000,
    requiredSkill: 8,
    requiredEducationLevel: 4,
    requiredDegree: "executive-finance-mba",
    requiredJobId: "investment-banker",
    requiredJobExperience: 3,
    requiredIntelligence: 82,
    requiredCharisma: 55,
    requiredDiscipline: 78,
    requiredReputation: 65,
  },

  {
    id: "nurse-assistant",
    title: "Nurse Assistant",
    category: "medical",
    careerPath: "Medical",
    nextJobId: "nurse",
    track: "medical",
    salary: 46000,
    requiredSkill: 1,
    requiredEducationLevel: 1,
    requiredIntelligence: 42,
    requiredCharisma: 25,
    requiredDiscipline: 42,
    requiredReputation: 5,
  },
  {
    id: "nurse",
    title: "Nurse",
    category: "medical",
    careerPath: "Medical",
    track: "medical",
    salary: 76000,
    requiredSkill: 3,
    requiredEducationLevel: 2,
    requiredDegree: "nursing-degree",
    requiredJobId: "nurse-assistant",
    requiredJobExperience: 2,
    requiredIntelligence: 58,
    requiredCharisma: 35,
    requiredDiscipline: 60,
    requiredReputation: 20,
  },
  {
    id: "doctor",
    title: "Doctor",
    category: "medical",
    careerPath: "Medical Doctor",
    nextJobId: "surgeon",
    track: "medical",
    salary: 160000,
    requiredSkill: 6,
    requiredEducationLevel: 4,
    requiredDegree: "medical-degree",
    requiredIntelligence: 78,
    requiredCharisma: 35,
    requiredDiscipline: 78,
    requiredReputation: 45,
  },
  {
    id: "surgeon",
    title: "Surgeon",
    category: "medical",
    careerPath: "Medical Doctor",
    track: "medical",
    salary: 320000,
    requiredSkill: 8,
    requiredEducationLevel: 4,
    requiredDegree: "surgery-specialization",
    requiredJobId: "doctor",
    requiredJobExperience: 3,
    requiredIntelligence: 90,
    requiredCharisma: 35,
    requiredDiscipline: 88,
    requiredReputation: 70,
  },

  {
    id: "legal-assistant",
    title: "Legal Assistant",
    category: "law",
    careerPath: "Law",
    nextJobId: "paralegal",
    track: "law",
    salary: 50000,
    requiredSkill: 1,
    requiredEducationLevel: 1,
    requiredIntelligence: 45,
    requiredCharisma: 35,
    requiredDiscipline: 35,
    requiredReputation: 5,
  },
  {
    id: "paralegal",
    title: "Paralegal",
    category: "law",
    careerPath: "Law",
    nextJobId: "lawyer",
    track: "law",
    salary: 70000,
    requiredSkill: 3,
    requiredEducationLevel: 2,
    requiredDegree: "legal-studies",
    requiredJobId: "legal-assistant",
    requiredJobExperience: 2,
    requiredIntelligence: 58,
    requiredCharisma: 45,
    requiredDiscipline: 50,
    requiredReputation: 20,
  },
  {
    id: "lawyer",
    title: "Lawyer",
    category: "law",
    careerPath: "Law",
    nextJobId: "judge",
    track: "law",
    salary: 145000,
    requiredSkill: 5,
    requiredEducationLevel: 3,
    requiredDegree: "law-degree",
    requiredJobId: "paralegal",
    requiredJobExperience: 3,
    requiredIntelligence: 75,
    requiredCharisma: 60,
    requiredDiscipline: 65,
    requiredReputation: 45,
  },
  {
    id: "judge",
    title: "Judge",
    category: "law",
    careerPath: "Law",
    track: "law",
    salary: 260000,
    requiredSkill: 8,
    requiredEducationLevel: 4,
    requiredDegree: "judicial-studies",
    requiredJobId: "lawyer",
    requiredJobExperience: 3,
    requiredIntelligence: 88,
    requiredCharisma: 65,
    requiredDiscipline: 80,
    requiredReputation: 80,
  },

  {
    id: "property-assistant",
    title: "Property Assistant",
    category: "realEstate",
    careerPath: "Real Estate",
    nextJobId: "real-estate-agent",
    track: "realEstate",
    salary: 42000,
    requiredSkill: 1,
    requiredEducationLevel: 0,
    requiredIntelligence: 30,
    requiredCharisma: 40,
    requiredDiscipline: 30,
    requiredReputation: 5,
  },
  {
    id: "real-estate-agent",
    title: "Real Estate Agent",
    category: "realEstate",
    careerPath: "Real Estate",
    nextJobId: "real-estate-developer",
    track: "realEstate",
    salary: 70000,
    requiredSkill: 3,
    requiredEducationLevel: 1,
    requiredDegree: "real-estate-license",
    requiredJobId: "property-assistant",
    requiredJobExperience: 2,
    requiredIntelligence: 35,
    requiredCharisma: 58,
    requiredDiscipline: 40,
    requiredReputation: 15,
  },
  {
    id: "real-estate-developer",
    title: "Real Estate Developer",
    category: "realEstate",
    careerPath: "Real Estate",
    nextJobId: "real-estate-mogul",
    track: "realEstate",
    salary: 180000,
    requiredSkill: 6,
    requiredEducationLevel: 2,
    requiredDegree: "property-development",
    requiredJobId: "real-estate-agent",
    requiredJobExperience: 3,
    requiredIntelligence: 58,
    requiredCharisma: 70,
    requiredDiscipline: 65,
    requiredReputation: 55,
  },
  {
    id: "real-estate-mogul",
    title: "Real Estate Mogul",
    category: "realEstate",
    careerPath: "Real Estate",
    track: "realEstate",
    salary: 300000,
    requiredSkill: 8,
    requiredEducationLevel: 4,
    requiredDegree: "real-estate-mba",
    requiredJobId: "real-estate-developer",
    requiredJobExperience: 3,
    requiredIntelligence: 72,
    requiredCharisma: 82,
    requiredDiscipline: 75,
    requiredReputation: 78,
  },

  {
    id: "content-creator",
    title: "Content Creator",
    category: "creative",
    careerPath: "Creative",
    nextJobId: "media-producer",
    track: "content",
    salary: 65000,
    requiredSkill: 2,
    requiredEducationLevel: 0,
    requiredIntelligence: 35,
    requiredCharisma: 60,
    requiredDiscipline: 35,
    requiredReputation: 20,
  },
  {
    id: "media-producer",
    title: "Media Producer",
    category: "creative",
    careerPath: "Creative",
    nextJobId: "creative-director",
    track: "content",
    salary: 95000,
    requiredSkill: 4,
    requiredEducationLevel: 1,
    requiredDegree: "media-degree",
    requiredJobId: "content-creator",
    requiredJobExperience: 2,
    requiredIntelligence: 48,
    requiredCharisma: 70,
    requiredDiscipline: 45,
    requiredReputation: 40,
  },
  {
    id: "creative-director",
    title: "Creative Director",
    category: "creative",
    careerPath: "Creative",
    nextJobId: "celebrity-entrepreneur",
    track: "content",
    salary: 150000,
    requiredSkill: 6,
    requiredEducationLevel: 2,
    requiredDegree: "creative-business",
    requiredJobId: "media-producer",
    requiredJobExperience: 3,
    requiredIntelligence: 60,
    requiredCharisma: 78,
    requiredDiscipline: 55,
    requiredReputation: 65,
  },
  {
    id: "celebrity-entrepreneur",
    title: "Celebrity Entrepreneur",
    category: "creative",
    careerPath: "Creative",
    track: "content",
    salary: 300000,
    requiredSkill: 8,
    requiredEducationLevel: 4,
    requiredDegree: "celebrity-business-mba",
    requiredJobId: "creative-director",
    requiredJobExperience: 3,
    requiredIntelligence: 65,
    requiredCharisma: 90,
    requiredDiscipline: 55,
    requiredReputation: 85,
  },
];